CREATE TABLE IF NOT EXISTS public.employees
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email_address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "position" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    surname character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT employees_pkey PRIMARY KEY (id),
    CONSTRAINT employees_email_address_key UNIQUE (email_address),
    CONSTRAINT employees_position_check CHECK ("position"::text = ANY (ARRAY['MANAGER'::character varying, 'ADMINISTRATOR'::character varying]::text[]))
);

ALTER TABLE IF EXISTS public.employees
    OWNER to postgres;