CREATE TABLE IF NOT EXISTS public.orders
(
    client_id integer NOT NULL,
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    creation_date timestamp(6) without time zone NOT NULL,
    updated_date timestamp(6) without time zone NOT NULL,
    status character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT fkm2dep9derpoaehshbkkatam3v FOREIGN KEY (client_id)
        REFERENCES public.clients (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT orders_status_check CHECK (status::text = ANY (ARRAY['NEW'::character varying, 'PROCESSING'::character varying, 'COMPLETED'::character varying, 'CANCELED'::character varying]::text[]))
);

ALTER TABLE IF EXISTS public.orders
    OWNER to postgres;